# Use Node.js official image
FROM node:18

# Set working directory
WORKDIR /app

# Install Redis server and global npm packages
RUN apt-get update && apt-get install -y redis-server \
    && npm install -g typescript ts-node

# Copy only package files first (for better Docker caching)
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Expose backend port
EXPOSE 4050

# Command to run your app
CMD ["npm", "start"]
