name: Build and Push Docker Images (Frontend & Backend)

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # -------- Frontend Build & Push --------
      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # -------- Backend Build & Push --------
      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./Backend

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
